[#intro]
= Введение

:idprefix: intro_
:cpp: C++

обновление до версии 1.90.0

link:https://en.wikipedia.org/wiki/Hash_table[Хеш-таблицы^] — это чрезвычайно популярные структуры данных в информатике, которые можно найти в той или иной форме практически в любом языке программирования. В то время как другие ассоциативные структуры, такие как красно-черные деревья (используемые в {cpp} в `std::set` и `std::map`), имеют логарифмическую сложность по времени для вставки и поиска, хеш-таблицы при правильной настройке выполняют эти операции в среднем за постоянное время и, как правило, работают намного быстрее.

{cpp} представил __неупорядоченные ассоциативные контейнеры__ `std::unordered_set`, `std::unordered_map`, `std::unordered_multiset` и `std::unordered_multimap` в {cpp}11, но исследования хеш-таблиц не прекращались с тех пор: достижения в архитектуре процессоров, такие как более мощные кеши, link:https://en.wikipedia.org/wiki/Single_instruction,_multiple_data[SIMD-операции] и все более доступные link:https://en.wikipedia.org/wiki/Multi-core_processor[многоядерные процессоры], открывают возможности для улучшенных структур данных на основе хеширования и новых сценариев использования, которые просто недостижимы для неупорядоченных ассоциативных контейнеров, как они были определены в 2011 году.

Boost.Unordered предлагает каталог хеш-контейнеров с различными уровнями соответствия стандартам, производительностью и предназначенными сценариями использования:

[caption=",",  title='Table {counter:table-counter}. Boost.Unordered containers']
[cols="1,1,.^1", frame=all,,  grid=all]
|===
^h|
^h|*На основе узлов*
^h|*Плоские*

^.^h|*Закрытая адресация*
^m|
boost::unordered_set +
boost::unordered_map +
boost::unordered_multiset +
boost::unordered_multimap
^|

^.^h|*Открытая адресация*
^m| boost::unordered_node_set +
boost::unordered_node_map
^m| boost::unordered_flat_set +
boost::unordered_flat_map

^.^h|*Параллельные*
^| `boost::concurrent_node_set` +
`boost::concurrent_node_map`
^| `boost::concurrent_flat_set` +
`boost::concurrent_flat_map`

|===

* **Контейнеры с закрытой адресацией** полностью соответствуют спецификации C++ для неупорядоченных ассоциативных контейнеров и обладают одной из самых быстрых реализаций на рынке в рамках технических ограничений, накладываемых требуемым стандартным интерфейсом.
* **Контейнеры с открытой адресацией** основаны на гораздо более быстрых структурах данных и алгоритмах (более чем в 2 раза быстрее в типичных сценариях), при этом незначительно отклоняясь от стандартного интерфейса для реализации. Существуют два варианта: **плоские** (самые быстрые) и **на основе узлов**, которые обеспечивают стабильность указателей при рехешировании за счет меньшей скорости.
* Наконец, **параллельные контейнеры** спроектированы и реализованы для использования в высокопроизводительных многопоточных сценариях. Их интерфейс радикально отличается от интерфейса обычных контейнеров C++. Предоставляются плоские и узловые варианты.

Все множества и отображения в Boost.Unordered инстанцируются аналогично `std::unordered_set` и `std::unordered_map` соответственно:

[source, c++]
----
namespace boost {
    template <
        class Key,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<Key> >
    class unordered_set;
    // аналогично для unordered_multiset, unordered_flat_set, unordered_node_set,
    // concurrent_flat_set и concurrent_node_set

    template <
        class Key, class Mapped,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<std::pair<Key const, Mapped> > >
    class unordered_map;
    // аналогично для unordered_multimap, unordered_flat_map, unordered_node_map,
    // concurrent_flat_map и concurrent_node_map
}
----

Хранение объекта в неупорядоченном ассоциативном контейнере требует как функции сравнения ключей, так и хеш-функции. Стандартные функциональные объекты в контейнерах поддерживают несколько базовых типов, включая целочисленные типы, типы с плавающей запятой, указатели и стандартные строки. Поскольку Boost.Unordered использует link:../../../../container_hash/index.html[boost::hash^], он также поддерживает некоторые другие типы, включая стандартные контейнеры. Для использования типов, не поддерживаемых этими методами, необходимо расширить Boost.Hash для поддержки типа или использовать собственные пользовательские предикаты равенства и хеш-функции. Подробнее см. в разделе xref:hash_equality.adoc#hash_equality[Предикаты равенства и хеш-функции].
