[#intro]
= 引言

:idprefix: intro_
:cpp: C++

更新至1.90.0

link:https://en.wikipedia.org/wiki/Hash_table[哈希表^]是极其流行的计算机数据结构，几乎可以在任何编程语言中以某种形式找到。而其他关联结构（如红黑树（在{cpp}中由`std::set`和`std::map`使用））的插入和查找具有对数时间复杂度，如果配置得当，哈希表则能在平均情况下以常数时间执行这些操作，并且通常快得多。

{cpp}在{cpp}11中引入了__无序关联容器__ `std::unordered_set`、`std::unordered_map`、`std::unordered_multiset`和`std::unordered_multimap`，但哈希表的研究并未止步：CPU架构的进步（如更强大的缓存、link:https://en.wikipedia.org/wiki/Single_instruction,_multiple_data[SIMD]操作以及日益普及的link:https://en.wikipedia.org/wiki/Multi-core_processor[多核处理器]）为改进的基于哈希的数据结构和新的应用场景开辟了可能性，这些是2011年规范的无序关联容器根本无法企及的。

Boost.Unordered提供了一系列具有不同标准合规级别、性能和预期使用场景的哈希容器：

[caption="，",  title='Table {counter:table-counter}. Boost.Unordered containers']
[cols="1,1,.^1", frame=all,,  grid=all]
|===
^h|
^h|*基于节点*
^h|*扁平*

^.^h|*闭地址法*
^m|
boost::unordered_set +
boost::unordered_map +
boost::unordered_multiset +
boost::unordered_multimap
^|

^.^h|*开地址法*
^m| boost::unordered_node_set +
boost::unordered_node_map
^m| boost::unordered_flat_set +
boost::unordered_flat_map

^.^h|*并发*
^| `boost::concurrent_node_set` +
`boost::concurrent_node_map`
^| `boost::concurrent_flat_set` +
`boost::concurrent_flat_map`

|===

* **闭地址法容器**完全符合C++无序关联容器的规范，并在标准接口所要求的技术约束下，实现了市场上最快的实现之一。
* **开地址法容器**依赖更快的数据结构和算法（在典型场景中快2倍以上），同时为了适应实现而略微偏离标准接口。有两种变体：**扁平型**（最快）和**基于节点型**，后者在重新哈希时提供指针稳定性，但速度较慢。
* 最后，**并发容器**专为高性能多线程场景设计和实现，其接口与常规C++容器截然不同。提供了扁平型和基于节点型两种变体。

Boost.Unordered中的所有集合和映射的实例化方式分别类似于`std::unordered_set`和`std::unordered_map`：

[source, c++]
----
namespace boost {
    template <
        class Key,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<Key> >
    class unordered_set;
    // 同样适用于unordered_multiset、unordered_flat_set、unordered_node_set、
    // concurrent_flat_set和concurrent_node_set

    template <
        class Key, class Mapped,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<std::pair<Key const, Mapped> > >
    class unordered_map;
    // 同样适用于unordered_multimap、unordered_flat_map、unordered_node_map、
    // concurrent_flat_map和concurrent_node_map
}
----

在无序关联容器中存储对象需要键相等函数和哈希函数。标准容器中的默认函数对象支持一些基本类型，包括整数类型、浮点类型、指针类型和标准字符串。由于Boost.Unordered使用link:../../../../container_hash/index.html[boost::hash^]，它还支持其他一些类型，包括标准容器。若要使用这些方法不支持的类型，您必须扩展Boost.Hash以支持该类型，或使用自定义的相等谓词和哈希函数。更多详情请参阅xref:hash_equality.adoc#hash_equality[相等谓词与哈希函数]部分。
