[#intro]
= Introduction

:idprefix: intro_
:cpp: C++

mise à jour vers la version 1.90.0

link:https://en.wikipedia.org/wiki/Hash_table[Les tables de hachage^] sont des structures de données informatiques extrêmement populaires et se retrouvent sous une forme ou une autre dans pratiquement tous les langages de programmation. Alors que d'autres structures associatives telles que les arbres rouge-noir (utilisés en {cpp} par `std::set` et `std::map`) ont une complexité logarithmique pour l'insertion et la recherche, les tables de hachage, si elles sont correctement configurées, effectuent ces opérations en temps constant en moyenne et sont généralement beaucoup plus rapides.

{cpp} a introduit les __conteneurs associatifs non ordonnés__ `std::unordered_set`, `std::unordered_map`, `std::unordered_multiset` et `std::unordered_multimap` dans {cpp}11, mais la recherche sur les tables de hachage n'a pas cessé depuis : les avancées dans les architectures de processeur telles que des caches plus puissants, les opérations link:https://en.wikipedia.org/wiki/Single_instruction,_multiple_data[SIMD] et la disponibilité croissante de link:https://en.wikipedia.org/wiki/Multi-core_processor[processeurs multicœurs] ouvrent des possibilités pour des structures de données basées sur le hachage améliorées et de nouveaux cas d'utilisation qui sont simplement hors de portée des conteneurs associatifs non ordonnés tels que spécifiés en 2011.

Boost.Unordered offre un catalogue de conteneurs de hachage avec différents niveaux de conformité aux normes, performances et scénarios d'utilisation prévus :

[caption=",",  title='Table {counter:table-counter}. Boost.Unordered containers']
[cols="1,1,.^1", frame=all,,  grid=all]
|===
^h|
^h|*À base de nœuds*
^h|*Plat*

^.^h|*Adressage fermé*
^m|
boost::unordered_set +
boost::unordered_map +
boost::unordered_multiset +
boost::unordered_multimap
^|

^.^h|*Adressage ouvert*
^m| boost::unordered_node_set +
boost::unordered_node_map
^m| boost::unordered_flat_set +
boost::unordered_flat_map

^.^h|*Concurrent*
^| `boost::concurrent_node_set` +
`boost::concurrent_node_map`
^| `boost::concurrent_flat_set` +
`boost::concurrent_flat_map`

|===

* Les **conteneurs à adressage fermé** sont entièrement conformes à la spécification C++ pour les conteneurs associatifs non ordonnés et présentent l'une des implémentations les plus rapides du marché dans les contraintes techniques imposées par l'interface standard requise.
* Les **conteneurs à adressage ouvert** reposent sur des structures de données et des algorithmes beaucoup plus rapides (plus de 2 fois plus rapides dans des scénarios typiques) tout en divergent légèrement de l'interface standard pour s'adapter à l'implémentation. Il existe deux variantes : **plat** (la plus rapide) et **à base de nœuds**, qui assurent la stabilité des pointeurs lors du rehachage au prix d'une vitesse moindre.
* Enfin, les **conteneurs concurrents** sont conçus et implémentés pour être utilisés dans des scénarios multithread hautes performances. Leur interface est radicalement différente de celle des conteneurs C++ classiques. Des variantes plat et à base de nœuds sont fournies.

Tous les ensembles et les cartes dans Boost.Unordered sont instanciés de manière similaire à `std::unordered_set` et `std::unordered_map`, respectivement :

[source, c++]
----
namespace boost {
    template <
        class Key,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<Key> >
    class unordered_set;
    // same for unordered_multiset, unordered_flat_set, unordered_node_set,
    // concurrent_flat_set and concurrent_node_set

    template <
        class Key, class Mapped,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<std::pair<Key const, Mapped> > >
    class unordered_map;
    // same for unordered_multimap, unordered_flat_map, unordered_node_map,
    // concurrent_flat_map and concurrent_node_map
}
----

Stocker un objet dans un conteneur associatif non ordonné nécessite à la fois une fonction d'égalité de clé et une fonction de hachage. Les objets fonction par défaut dans les conteneurs standards prennent en charge quelques types de base, notamment les types entiers, les types à virgule flottante, les types pointeur et les chaînes de caractères standards. Comme Boost.Unordered utilise link:../../../../container_hash/index.html[boost::hash^], il prend également en charge d'autres types, y compris les conteneurs standards. Pour utiliser des types non pris en charge par ces méthodes, vous devez étendre Boost.Hash pour prendre en charge le type ou utiliser vos propres prédicats d'égalité et fonctions de hachage personnalisés. Consultez la section xref:hash_equality.adoc#hash_equality[Prédicats d'égalité et fonctions de hachage] pour plus de détails.
