[#intro]
= はじめに

:idprefix: intro_
:cpp: C++

1.90.0への更新

link:https://en.wikipedia.org/wiki/Hash_table[ハッシュテーブル^]は非常に人気のあるコンピュータデータ構造であり、事実上あらゆるプログラミング言語で何らかの形で見つけることができる。一方、赤黒木（{cpp}では`std::set`や`std::map`で使用される）のような他の連想構造は挿入と検索に対数時間計算量を要するのに対し、ハッシュテーブルは、適切に設定されていれば、これらの操作を平均的に定数時間で実行し、一般的にはるかに高速である。

{cpp}は、{cpp}11で__非順序連想コンテナ__ `std::unordered_set`、`std::unordered_map`、`std::unordered_multiset`、`std::unordered_multimap`を導入した。しかし、それ以降もハッシュテーブルの研究は止まっていない：より強力なキャッシュ、link:https://en.wikipedia.org/wiki/Single_instruction,_multiple_data[SIMD]操作、そしてますます利用可能になっているlink:https://en.wikipedia.org/wiki/Multi-core_processor[マルチコアプロセッサ]といったCPUアーキテクチャの進歩により、2011年に規定された非順序連想コンテナの単純な範囲を超えた、改良されたハッシュベースのデータ構造と新しいユースケースの可能性が開かれた。

Boost.Unorderedは、さまざまな標準準拠レベル、パフォーマンス、および想定される使用シナリオを持つハッシュコンテナのカタログを提供する：

[caption=",",  title='Table {counter:table-counter}. Boost.Unordered containers']
[cols="1,1,.^1", frame=all,,  grid=all]
|===
^h|
^h|*ノードベース*
^h|*フラット*

^.^h|*閉アドレス法*
^m|
boost::unordered_set +
boost::unordered_map +
boost::unordered_multiset +
boost::unordered_multimap
^|

^.^h|*開アドレス法*
^m| boost::unordered_node_set +
boost::unordered_node_map
^m| boost::unordered_flat_set +
boost::unordered_flat_map

^.^h|*並行*
^| `boost::concurrent_node_set` +
`boost::concurrent_node_map`
^| `boost::concurrent_flat_set` +
`boost::concurrent_flat_map`

|===

* **閉アドレス法コンテナ**は、非順序連想コンテナのC++仕様に完全に準拠しており、必要な標準インターフェースによって課せられる技術的制約の中で、市場で最も高速な実装の1つを特徴としている。
* **開アドレス法コンテナ**は、標準インターフェースからわずかに逸脱して実装を可能にすることで、はるかに高速なデータ構造とアルゴリズム（典型的なシナリオでは2倍以上高速）に依存している。2つのバリエーションがある：**フラット**（最速）と**ノードベース**（再ハッシュ時のポインタ安定性を提供するが、その分遅い）。
* 最後に、**並行コンテナ**は、高性能なマルチスレッドシナリオで使用するために設計および実装されている。それらのインターフェースは通常のC++コンテナとは根本的に異なる。フラットとノードベースのバリエーションが提供されている。

Boost.Unorderedのすべてのセットとマップは、それぞれ`std::unordered_set`および`std::unordered_map`と同様にインスタンス化される：

[source, c++]
----
namespace boost {
    template <
        class Key,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<Key> >
    class unordered_set;
    // same for unordered_multiset, unordered_flat_set, unordered_node_set,
    // concurrent_flat_set and concurrent_node_set

    template <
        class Key, class Mapped,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<std::pair<Key const, Mapped> > >
    class unordered_map;
    // same for unordered_multimap, unordered_flat_map, unordered_node_map,
    // concurrent_flat_map and concurrent_node_map
}
----

オブジェクトを非順序連想コンテナに格納するには、キー等価関数とハッシュ関数の両方が必要である。標準コンテナのデフォルト関数オブジェクトは、整数型、浮動小数点型、ポインタ型、標準文字列を含むいくつかの基本型をサポートしている。Boost.Unorderedはlink:../../../../container_hash/index.html[boost::hash^]を使用するため、標準コンテナを含む他のいくつかの型もサポートしている。これらのメソッドでサポートされていない型を使用するには、Boost.Hashを拡張してその型をサポートするか、独自のカスタム等価述語とハッシュ関数を使用する必要がある。詳細については、xref:hash_equality.adoc#hash_equality[等価述語とハッシュ関数]のセクションを参照のこと。
