[#regular]
= Обычные контейнеры

:idprefix: regular_

Контейнеры с закрытой адресацией Boost.Unordered (`boost::unordered_set`, `boost::unordered_map`, `boost::unordered_multiset` и `boost::unordered_multimap`) полностью соответствуют спецификации C++ для неупорядоченных ассоциативных контейнеров. Поэтому для тех, кто знает, как использовать `std::unordered_set`, `std::unordered_map` и т.д., их одноименные аналоги в Boost.Unordered являются прямыми заменами. Интерфейс контейнеров с открытой адресацией (`boost::unordered_node_set`, `boost::unordered_node_map`, `boost::unordered_flat_set` и `boost::unordered_flat_map`) очень похож, но имеет некоторые незначительные отличия, перечисленные в специальном разделе xref:compliance.adoc#compliance_open_addressing_containers[соответствия стандарту].


Для читателей без опыта работы с хеш-контейнерами, но знакомых с обычными ассоциативными контейнерами (`std::set`, `std::map`, `std::multiset` и `std::multimap`), контейнеры Boost.Unordered используются аналогичным образом:

[source, cpp]
----
typedef boost::unordered_map<std::string, int> map;
map x;
x["one"] = 1;
x["two"] = 2;
x["three"] = 3;

assert(x.at("one") == 1);
assert(x.find("missing") == x.end());
----

Но поскольку элементы не упорядочены, вывод:

[source, c++]
----
for(const map::value_type& i: x) {
    std::cout<<i.first<<","<<i.second<<"\n";
}
----

может быть в любом порядке. Например, он может быть таким:

[source]
----
two,2
one,1
three,3
----

Есть и другие различия, которые перечислены в разделе xref:regular.adoc#comparison[Сравнение с ассоциативными контейнерами].

== Инвалидация итераторов

Не указано, как функции-члены, кроме `rehash` и `reserve`, влияют на количество сегментов, хотя `insert` может инвалидировать итераторы только тогда, когда вставка приводит к тому, что нагрузка контейнера превышает максимально допустимую. Для большинства реализаций это означает, что `insert` будет изменять количество сегментов только в этом случае. Итераторы могут быть инвалидированы вызовами `insert`, `rehash` и `reserve`.

Что касается указателей и ссылок, они никогда не инвалидируются для нодных контейнеров (`boost::unordered_[multi]set`, `boost::unordered_[multi]map`, `boost::unordered_node_set`, `boost::unordered_node_map`), но будут инвалидироваться при рехешировании для `boost::unordered_flat_set` и `boost::unordered_flat_map`: это связано с тем, что эти контейнеры хранят элементы непосредственно в своих сегментах, поэтому при выделении нового массива сегментов элементы должны быть перенесены посредством перемещающего конструирования.

Аналогично использованию `reserve` для ``vector``, может быть хорошей идеей вызвать `reserve` перед вставкой большого количества элементов. Это позволит выполнить дорогостоящий рехеш заранее и сохранять итераторы, будучи уверенным, что они не будут инвалидированы. Если вы вставляете `n` элементов в контейнер `x`, вы можете сначала вызвать:

```

x.reserve(n);

```

Примечание:: `reserve(n)` резервирует место как минимум для `n` элементов, выделяя достаточно сегментов, чтобы не превысить максимальный коэффициент загрузки.
+
Поскольку максимальный коэффициент загрузки определяется как количество элементов, деленное на общее количество доступных сегментов, эта функция логически эквивалентна:
+
```

x.rehash(std::ceil(n / x.max_load_factor()))

```
+
См. xref:reference/unordered_map.adoc#unordered_map_rehash[справочник для получения дополнительной информации] о функции `rehash`.

[#comparison]

:idprefix: comparison_

== Сравнение с ассоциативными контейнерами

[caption=",",  title='Table {counter:table-counter} Interface differences']
[cols="1,1", frame=all,,  grid=rows]
|===
|Ассоциативные контейнеры |Неупорядоченные ассоциативные контейнеры

|Параметризуются отношением упорядочивания `Compare`
|Параметризуются функциональным объектом `Hash` и отношением эквивалентности `Pred`

|Ключи можно сравнивать с помощью `key_compare`, доступного через функцию-член `key_comp()`, значения можно сравнивать с помощью `value_compare`, доступного через функцию-член `value_comp()`.
|Ключи можно хешировать с помощью `hasher`, доступного через функцию-член `hash_function()`, и проверять на эквивалентность с помощью `key_equal`, доступного через функцию-член `key_eq()`. Нет функционального объекта для сравнения или хеширования значений.

|Конструкторы имеют дополнительные необязательные параметры для объекта сравнения.
|Конструкторы имеют дополнительные необязательные параметры для начального минимального количества сегментов, функции хеширования и объекта эквивалентности.

|Ключи `k1`, `k2` считаются эквивалентными, если `!Compare(k1, k2) && !Compare(k2, k1)`.
|Ключи `k1`, `k2` считаются эквивалентными, если `Pred(k1, k2)`

|Функция-член `lower_bound(k)` и `upper_bound(k)`
|Нет эквивалента. Поскольку элементы не упорядочены, `lower_bound` и `upper_bound` не имеют смысла.

|`equal_range(k)` возвращает пустой диапазон в позиции, куда был бы вставлен `k`, если `k` отсутствует в контейнере.
|`equal_range(k)` возвращает диапазон в конце контейнера, если `k` отсутствует в контейнере. Он не может возвращать позиционированный диапазон, так как `k` может быть вставлен в несколько мест. +
**Контейнеры с закрытой адресацией:** Чтобы узнать сегмент, в который был бы вставлен `k`, используйте `bucket(k)`. Но помните, что вставка может вызвать рехеш контейнера, что означает, что элемент может быть вставлен в другой сегмент.

|`iterator`, `const_iterator` относятся к двунаправленной категории.
|`iterator`, `const_iterator` относятся как минимум к прямой категории.

|Итераторы, указатели и ссылки на элементы контейнера никогда не инвалидируются.
|xref:regular.adoc#regular_iterator_invalidation[Итераторы могут быть инвалидированы вызовами insert или rehash]. +
**Нодные контейнеры:** Указатели и ссылки на элементы контейнера никогда не инвалидируются. +
**Плоские контейнеры:** Указатели и ссылки на элементы контейнера инвалидируются при рехешировании.

|Итераторы проходят по контейнеру в порядке, определенном объектом сравнения.
|Итераторы проходят по контейнеру в произвольном порядке, который может меняться при вставке элементов, хотя эквивалентные элементы всегда находятся рядом.

|Нет эквивалента
|**Контейнеры с закрытой адресацией:** Локальные итераторы могут использоваться для обхода отдельных сегментов. (Порядок локальных итераторов и итераторов не обязательно должен соответствовать.)

|Могут сравниваться с помощью операторов `==`, `!=`, `<`, `\<=`, `>`, `>=`.
|Могут сравниваться с помощью операторов `==` и `!=`.

|
|При вставке с подсказкой реализации могут игнорировать подсказку.

|===

---

[caption=",",  title='Table {counter:table-counter} Complexity Guarantees']
[cols="1,1,1", frame=all,,  grid=rows]
|===
|Операция |Ассоциативные контейнеры |Неупорядоченные ассоциативные контейнеры

|Создание пустого контейнера
|константа
|O(_n_), где _n_ — минимальное количество сегментов.

|Создание контейнера из диапазона из _N_ элементов
|O(_N log N_), O(_N_), если диапазон отсортирован с помощью `value_comp()`
|Средний случай O(_N_), худший случай O(_N^2^_)

|Вставка одного элемента
|логарифмическая
|Средний случай константа, худший случай линейная

|Вставка одного элемента с подсказкой
|Амортизированная константа, если элементы вставляются сразу после подсказки, в противном случае логарифмическая
|Средний случай константа, худший случай линейная (т.е. как при обычной вставке).

|Вставка диапазона из _N_ элементов
|_N_ log(`size()` + _N_)
|Средний случай O(_N_), худший случай O(_N_ * `size()`)

|Удаление по ключу `k`
|O(log(`size()`) + `count(k)`)
|Средний случай: O(`count(k)`), худший случай: O(`size()`)

|Удаление одного элемента по итератору
|Амортизированная константа
|Средний случай: O(1), худший случай: O(`size()`)

|Удаление диапазона из _N_ элементов
|O(log(`size()`) + _N_)
|Средний случай: O(_N_), худший случай: O(`size()`)

|Очистка контейнера
|O(`size()`)
|O(`size()`)

|Поиск
|логарифмическая
|Средний случай: O(1), худший случай: O(`size()`)

|Подсчет
|O(log(`size()`) + `count(k)`)
|Средний случай: O(1), худший случай: O(`size()`)

|`equal_range(k)`
|логарифмическая
|Средний случай: O(`count(k)`), худший случай: O(`size()`)

|`lower_bound`, `upper_bound`
|логарифмическая
|н/д

|===
